### ISSUE TITLE
Class 'BrianFaust\ServiceProvider\AbstractServiceProvider' not found

### ISSUE THREAD

**Issue by rmdwirizki** [faustbrian/Laravel-Invoice#4]
FatalErrorException in InvoiceServiceProvider.php line 16:
Class 'BrianFaust\ServiceProvider\AbstractServiceProvider' not found

How to fix this? 
Where is the AbstractServiceProvider class anyway? I can't find it in the vendor package

**Comment by rmdwirizki** [comment]
fixed by running
`composer require faustbrian/laravel-service-provider`

**Comment by c1t1zen** [comment]
Does it work with you @rmdwirizki  ?

**Comment by rmdwirizki** [comment]
@c1t1zen yes it is.
looks like it require another dependencies package from https://github.com/faustbrian/Laravel-Service-Provider

But, I end up not using this anymore because this package lack a default invoice blade template and it implement _void return type_ that needs php .7.1.

**Comment by faustbrian** [comment]
There is no default template because that should be your job when you develop a project for a client. Also I only use the most recent versions of any software I don't support anything below PHP 7.1.
